export const replyEvents = {
  REPLY_ADDED: "REPLY_ADDED",
  REPLY_MARKED_AS_BEST_ANSWER: "REPLY_MARKED_AS_BEST_ANSWER",
  REPLY_UNMARKED_AS_BEST_ANSWER: "REPLY_UNMARKED_AS_BEST_ANSWER"
};

export const favoriteEvents = {
  REPLY_FAVORITED: "REPLY_FAVORITED",
  REPLY_UNFAVORITED: "REPLY_UNFAVORITED"
};
